# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar csproj e restaurar dependências
COPY WebfamilyCrud/*.csproj ./WebfamilyCrud/
RUN dotnet restore WebfamilyCrud/WebfamilyCrud.csproj

# Copiar todo o código e compilar
COPY . .
WORKDIR /src/WebfamilyCrud
RUN dotnet publish WebfamilyCrud.csproj -c Release -o /app/publish

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "WebfamilyCrud.dll"]
